import type { EntryResponse } from '$lib/api/entries';
import type { DashboardSummaryResponse } from '$lib/api/dashboard';
import type { UserPreferencesResponse } from '$lib/api/preferences';
import { localIsoDate, shiftIsoDate } from '$lib/utils/streak';

const today = localIsoDate(new Date());

export const mockEntries: EntryResponse[] = Array.from({ length: 14 }, (_, idx) => {
  const date = shiftIsoDate(today, -idx);
  return {
    id: `mock-entry-${idx}`,
    user_id: 'mock-user',
    entry_date: date,
    slot: 'day',
    mood_score: 3 + ((idx + 1) % 3),
    energy: 2 + (idx % 4),
    stress: 2 + ((idx + 2) % 3),
    cycle_day: idx < 10 ? idx + 1 : null,
    source: 'direct',
    work_context: idx % 6 === 0 ? 'weekend' : 'office',
    note: idx === 0 ? 'Mock entry generated by Force Visualizations.' : null,
    created_at: `${date}T09:00:00Z`,
    updated_at: `${date}T09:00:00Z`,
  };
});

export const mockDashboardSummary: DashboardSummaryResponse = {
  entry_count: 42,
  insight_tier: 'developing',
  confidence_score: 0.66,
};

export const mockUserPreferences: UserPreferencesResponse = {
  user_id: 'mock-user',
  analytics_enabled: true,
  onboarding_retro_completed: true,
  onboarding_profile_completed: true,
  dismissed_insight_keys: [],
  reached_milestone_keys: [],
  last_seen_insight_at: null,
  created_at: `${today}T09:00:00Z`,
  updated_at: `${today}T09:00:00Z`,
};
